# src/Sdz/BlogBundle/Resources/config/routing.yml
#
sdzblog_index:
    pattern:   /
    defaults:  { _controller: SdzBlogBundle:Blog:index }

sdzblog_voir:
    pattern:   /article/{id}
    defaults:  { _controller: SdzBlogBundle:Blog:voir }
    requirements:
        id: \d+

sdzblog_ajouter:
    pattern:   /ajouter
    defaults:  { _controller: SdzBlogBundle:Blog:ajouter }

sdzblog_modifier:
    pattern:   /modifier/{id}
    defaults:  { _controller: SdzBlogBundle:Blog:modifier }
    requirements:
        id:  \d+

sdzblog_supprimer:
    pattern:   /supprimer/{id}
    defaults:  { _controller: SdzBlogBundle:Blog:supprimer }
    requirements:
        id:  \d+

sdzblog_test:
    pattern:   /test
    defaults:  { _controller: SdzBlogBundle:Blog:test }

sdzblog_contact:
    pattern:   /contact
    defaults:  { _controller: SdzBlogBundle:Blog:contact }
